apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: manyfold
name: app-template
version: 3.7.3
releaseName: manyfold
repo: https://bjw-s.github.io/helm-charts
valuesFile: values.yaml
