controllers:
  manyfold:
    strategy: Recreate
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/manyfoldstudio
          tag: V0.111.2-ls81
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          PUID: 1000
          PGID: 1000
          DARK_MODE: true
          SECRET_KEY_BASE:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: api.txt
          DATABASE_ADAPTER: postgresql
          DATABASE_HOST:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: database.txt
          DATABASE_PORT:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: database.txt
          DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: database.txt
          DATABASE_USER:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: database.txt
          DATABASE_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: database.txt
          REDIS_URL:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: api.txt

  redis:
    strategy: Recreate
    containers:
      app:
        image:
          repository: redis
          tag: "7.4.3"
          pullPolicy: IfNotPresent
        env:
          REDIS_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: api.txt

  postgres:
    strategy: Recreate
    containers:
      app:
        image:
          repository: postgres
          tag: "16.9"
          pullPolicy: IfNotPresent
        env:
          POSTGRES_USER:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: database.txt
          POSTGRES_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: database.txt
          POSTGRES_DB:
            valueFrom:
              secretKeyRef:
                name: manyfold-vault-secrets
                key: database.txt

service:
  app:
    controller: manyfold
    ports:
      http:
        port: 3000

  redis:
    controller: redis
    ports:
      redis:
        port: 6379

  postgres:
    controller: postgres
    ports:
      postgres:
        port: 5432

ingress:
  app:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      external-dns.alpha.kubernetes.io/internal-hostname: manyfold.sievert.fun
    hosts:
    - host: manyfold.sievert.fun
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: app
          port: http
    tls:
    - secretName: manyfold-tls
      hosts:
      - manyfold.sievert.fun

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: khal-drogo-nfs
    size: 1Gi
    globalMounts:
    - path: /config

  redis:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: khal-drogo-nfs
    size: 1Gi

  postgres:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: khal-drogo-nfs
    size: 1Gi
