apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/smb-media

patches:
  - target:
      version: v1
      kind: PersistentVolume
      name: smb-media
    patch: |-
      - op: replace
        path: /metadata/name
        value: smb-readarr
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: smb-media
    patch: |-
      - op: replace
        path: /metadata/name
        value: smb-readarr

generators:
- helmChart.yaml

namespace: readarr
