apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: sabnzbd
name: app-template
version: 3.7.3
releaseName: sabnzbd
repo: https://bjw-s-labs.github.io/helm-charts
valuesFile: values.yaml
