# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:2zaEVjrCzRZNpPw3ipRYjKs7gViVJttF9zrUKj2ghSNWmbojo2cqtg==,iv:p+EezcuQj2p8LUtq2Yr2P8cejCooijtW30PS6Iq0D3I=,tag:A/xw5bnnjONUQMzWiFjquw==,type:str]
sops:
  age:
    - recipient: age1jj9jc77qz0jg9s7cl9s7a34mnkkn6wqgh3zvlneggnvdrx5gdu7q9msghy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZHRFS1pRQWNPRDlmcmlr
        WE5DZGxJbGRHTkNoQjZyMjVhbFYyQkZBUFJJCmJFdkgxajJvK2ZueFU2Y3Q5cjFp
        dWNWcjY2Mmw0TjBFNzNad0ZsbElHa2sKLS0tIEtjaUU1WWphTEJYRENWdTlIY3Bl
        Wkp5N3U1YVZpbjVveVdBbHZIM3lkZncKkr7Znfqxds4EybgzIDFdAz7Wq8X3ftM+
        D9hT3eqOw2Blal1TMprzHFdER+IU2/5Gg4t7bumcfnpN8S76q/jHNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T22:38:27Z"
  mac: ENC[AES256_GCM,data:gI5AWcKqX+4d1WujpPdmmoOS6TN//Mwsub2bX6luYTfFXX1PYSsfM+fgDUbsO/dd0IJqRTz5LYc6fPWT/iRITLTfzLb0DUlB/NQD4kkVe5fLAYG5r+1Nftpk4aQLC3WnBPbcXeyrlSYziEgLWdtAUTlduzCFCFhvqH2gxdeKank=,iv:N53aJLkVFStuGhxjmc34sgyYrf4qoI2eL8CxaF/5GTc=,tag:Tkpd7ajrTx75+iq5PF7xxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
