apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: keycloak
name: keycloak
version: 24.4.13
releaseName: keycloak
repo: https://charts.bitnami.com/bitnami
valuesFile: values.yaml
