apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: keycloak
name: keycloak
version: 24.4.13
releaseName: keycloak
repo: oci://registry-1.docker.io/bitnamicharts
valuesFile: values.yaml
