proxy: edge
production: true
auth:
  existingSecret: keycloak-secrets
  passwordSecretKey: keycloak-password

ingress:
  enabled: true
  ingressClassName: cilium
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    external-dns.alpha.kubernetes.io/internal-hostname: keycloak.sievert.fun
  hostname: keycloak.sievert.fun
  path: /
  tls: true

adminIngress:
  enabled: false
  ingressClassName: cilium
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    external-dns.alpha.kubernetes.io/internal-hostname: keycloak-admin.sievert.fun
  hostname: keycloak-admin.sievert.fun
  path: /
  tls: true

postgresql:
  enabled: true
  auth:
    existingSecret: keycloak-secrets
  primary:
    persistence:
      enabled: true
      storageClass: khal-drogo-nfs
