apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: vault
name: vault
version: 0.30.0
namespace: vault
releaseName: vault
repo: https://helm.releases.hashicorp.com
valuesFile: values.yaml 