apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: notifiarr
name: app-template
version: 3.7.3
releaseName: notifiarr
repo: https://bjw-s-labs.github.io/helm-charts
valuesFile: values.yaml
