apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: ollama
name: app-template
version: 3.7.3
releaseName: ollama
repo: https://otwld.github.io/ollama-helm/
valuesFile: values.yaml
