ollama:
  enabled: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    external-dns.alpha.kubernetes.io/internal-hostname: chat.sievert.fun
  host: chat.sievert.fun
  tls:
    - secretName: chat-tls
      hosts:
        - chat.sievert.fun
persistence:
  enabled: true
  storageClass: khal-drogo-nfs