# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.42.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.42.10"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "tuf1"
    ipAddress: "192.168.42.254"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/87febee00655db97caaa11a35c2544908122c0085e789451755e73140dddaa6b
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "24:4b:fe:8d:e1:0e"
        dhcp: false
        addresses:
          - "192.168.42.254/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.42.1"
        mtu: 1500
        vip:
          ip: "192.168.42.10"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

