# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.42.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.42.10"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "tuf1"
    ipAddress: "192.168.42.254"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    #talosImageURL: factory.talos.dev/installer/8f978bbd93627852c41baa0c58804b6f871319f6700024d0de471b7b384863ad
    talosImageURL: factory.talos.dev/installer/8f978bbd93627852c41baa0c58804b6f871319f6700024d0de471b7b384863ad
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "24:4b:fe:8d:e1:0e"
        dhcp: false
        addresses:
          - "192.168.42.254/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.42.1"
        mtu: 1500
        vip:
          ip: "192.168.42.10"
    # schematic:
    #   customization:
    #     systemExtensions:
    #       officialExtensions:
    #         - siderolabs/amd-ucode
    #         - siderolabs/iscsi-tools
    #         - siderolabs/nonfree-kmod-nvidia-production
    #         - siderolabs/nvidia-container-toolkit-production
    #         - siderolabs/tailscale
    #         - siderolabs/intel-ucode
    patches:
      - "@./patches/tuf1/nvidia.yaml"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

