apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/qnap-dev/QNAP-CSI-PlugIn/Deploy/crds?ref=v1.4.0
  - github.com/qnap-dev/QNAP-CSI-PlugIn/Deploy/Trident?ref=v1.4.0
#  - storage.yaml
