ingressRoute:
  dashboard:
    # -- Create an IngressRoute for the dashboard
    enabled: true

service:
  enabled: true
  ## -- Single service is using `MixedProtocolLBService` feature gate.
  ## -- When set to false, it will create two Service, one for TCP and one for UDP.
  single: true
  type: LoadBalancer
  # -- Additional annotations applied to both TCP and UDP services (e.g. for cloud provider specific config)
  annotations:
      external-dns.alpha.kubernetes.io/hostname: traefik.sievert.fun
