provider:
  name: cloudflare

policy: sync # or upsert-only

sources:
  - service
  - ingress
  - traefik-proxy

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey
rbac:
  create: true
