apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cleanuperr
name: app-template
version: 3.7.3
releaseName: cleanuperr
repo: https://bjw-s.github.io/helm-charts
valuesFile: values.yaml
