apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:uZz+Blkd23cOQ/qFPRzpzp2gfg==,iv:HLS+3Ir9U8aiA9YR0yYCLmW+CdA8mcU6x2VA3G8NKJU=,tag:s7xKOiL8WphdIBygpjJWew==,type:str]
sops:
  age:
    - recipient: age1jj9jc77qz0jg9s7cl9s7a34mnkkn6wqgh3zvlneggnvdrx5gdu7q9msghy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRDVLeDZ0NDFLdk91VWdZ
        cTA0VDMyMWNOTDgvMTI4L3NobEJIMWlkWmhBClFlT3ZCMHB4T2s1R2lZSG1pT0FH
        bWRJbmNoaUJwR2N6U1ZwYWxQZFlzbEUKLS0tIGFrVFAzZWJ1Z0hocHB0SlhORnpz
        akZKNUU0aUhMR0RvaUp3UVlYYXpzdUUKyaldorj741VoL835Io5EA2UzmVsJfdHt
        pcHpWfKnOl2oKSoZZ36XV4+8DxxX0gS9c91FdwDSf9xajZZ4amFEfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T22:38:27Z"
  mac: ENC[AES256_GCM,data:+Hj129c3apAxN6/mng7HNt0ytyyBPJuQBLc36voNzCMcDYF4cQql5dOo24UB0Xh6oFL8eVHYMrStCK01wvrcyZIY+wehide442lRwASXdnjdjAdIYSOh9TD/aKeH1dHlMhn4t99bR6g06kah8v+/QEwsDgXx9NsJ/9x0gfIlIQU=,iv:Q9CgyRdR3Kd+L2lgo6G0kT4T+I2X1aM4lok06bpGCAw=,tag:9xlnw1K/rzAzuxWO54PMGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
